name: build-stake-bpf

on:
  workflow_dispatch:
    inputs:
      stake_ref:
        description: "Branch or tag of solana-program/stake to build (e.g., main or v1.0.0)"
        type: string
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo (for provenance only)
        uses: actions/checkout@v4

      - name: Checkout solana-program/stake
        uses: actions/checkout@v4
        with:
          repository: solana-program/stake
          ref: ${{ github.event.inputs.stake_ref }}
          path: stake-src

      - name: System deps
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates git pkg-config libssl-dev build-essential clang llvm lld cmake jq

      - name: Install Rust (host)
        run: |
          set -euxo pipefail
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          rustup default stable
          rustup --version
          cargo --version

      - name: Install Agave CLI (for cargo-build-sbf)
        run: |
          set -euxo pipefail
          # Pin to the same Agave installer you’ve been using; adjust tag if you like
          AGAVE_VERSION=v2.3.9
          curl -sSfL "https://github.com/anza-xyz/agave/releases/download/${AGAVE_VERSION}/agave-install-init-x86_64-unknown-linux-gnu" -o agave-install-init
          chmod +x agave-install-init
          ./agave-install-init "${AGAVE_VERSION}"

          AGAVE_BIN="$HOME/.local/share/agave/install/active_release/bin"
          SOLANA_BIN="$HOME/.local/share/solana/install/active_release/bin"

          if [ -x "$AGAVE_BIN/cargo-build-sbf" ]; then
            echo "$AGAVE_BIN" >> "$GITHUB_PATH"
          elif [ -x "$SOLANA_BIN/cargo-build-sbf" ]; then
            echo "$SOLANA_BIN" >> "$GITHUB_PATH"
          else
            echo "cargo-build-sbf not found after install"
            find "$HOME/.local/share" -maxdepth 6 -type f -name 'cargo-build-sbf' -print || true
            exit 1
          fi

          which cargo-build-sbf
          cargo-build-sbf --version || true
          command -v agave && agave --version || true
          command -v solana && solana --version || true

      - name: Build Stake BPF (with required feature)
        working-directory: stake-src/program
        run: |
          set -euxo pipefail
          # Per repo docs, you must enable the BPF entrypoint feature
          cargo-build-sbf --features bpf-entrypoint

      - name: Collect artifact
        run: |
          set -euxo pipefail
          mkdir -p artifacts
          # Default location created by cargo build-sbf
          so_path="stake-src/target/deploy/solana_stake_program.so"
          if [ ! -f "$so_path" ]; then
            # Fallback search if target path differs
            so_path="$(find stake-src/target -type f -name 'solana_stake_program*.so' | head -n1 || true)"
          fi
          if [ -z "$so_path" ]; then
            echo "Could not find solana_stake_program.so under stake-src/target"
            find stake-src/target -maxdepth 4 -type f -name '*.so' -print || true
            exit 1
          fi
          cp "$so_path" artifacts/solana_stake_program.so

          # Minimal provenance
          (cd stake-src && git rev-parse HEAD) > artifacts/stake_repo_commit.txt
          (cargo-build-sbf --version || true) > artifacts/cargo_build_sbf_version.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: solana_stake_program
          path: artifacts/*
