name: build-stake-sbf
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates git pkg-config libssl-dev build-essential
      
      - name: Install Rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          rustup toolchain install nightly
          rustup default nightly
          rustc --version
          cargo --version
      
      - name: Install Agave CLI (v2.3.9)
        run: |
          curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.3.9/agave-install-init-x86_64-unknown-linux-gnu -o agave-install-init
          chmod +x agave-install-init
          ./agave-install-init v2.3.9
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/share/agave/install/active_release/bin" >> "$GITHUB_PATH"
          which cargo-build-sbf
          cargo-build-sbf --version
      
      - name: Build stake
        run: cargo-build-sbf
      
      - uses: actions/upload-artifact@v4
        with:
          name: solana_stake_program.so
          path: target/deploy/solana_stake_program.so
