name: build-sbf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Agave CLI v2.4.10
        run: |
          set -eux
          curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.4.10/agave-install-init-x86_64-unknown-linux-gnu -o agave-install-init
          chmod +x agave-install-init
          ./agave-install-init v2.4.10
          echo "$HOME/.local/share/agave/install/active_release/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      
      - name: Show tool versions
        run: |
          set -eux
          which cargo-build-sbf
          cargo-build-sbf --version
      
      - name: Build stake (SBF)
        run: |
          set -eux
          cargo-build-sbf --manifest-path programs/stake/Cargo.toml
      
      - name: Build vote (SBF)
        run: |
          set -eux
          cargo-build-sbf --manifest-path programs/vote/Cargo.toml
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbf-artifacts
          path: target/deploy/*.so
