name: build-sbf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream Agave v2.3.9
        uses: actions/checkout@v4
        with:
          repository: anza-xyz/agave
          ref: v2.3.9
          fetch-depth: 0
      
      - name: Build stake+vote with Agave CLI inside container
        run: |
          set -eux
          docker run --rm -v "$PWD:/work" -w /work --platform=linux/amd64 ubuntu:22.04 bash -lc '
            apt-get update &&
            apt-get install -y curl ca-certificates git pkg-config libssl-dev build-essential &&
            curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.3.9/agave-install-init-x86_64-unknown-linux-gnu -o /usr/local/bin/agave-install-init &&
            chmod +x /usr/local/bin/agave-install-init &&
            /usr/local/bin/agave-install-init v2.3.9 &&
            export PATH="$HOME/.local/share/agave/install/active_release/bin:$PATH" &&
            cargo-build-sbf --manifest-path programs/stake/Cargo.toml -- --locked &&
            cargo-build-sbf --manifest-path programs/vote/Cargo.toml -- --locked &&
            ls -l target/deploy/*.so
          '
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbf-artifacts
          path: target/deploy/*.so
