name: build-sbf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream Agave v2.3.9
        uses: actions/checkout@v4
        with:
          repository: anza-xyz/agave
          ref: v2.3.9
          fetch-depth: 0
      
      - name: Install system deps + Rust + Agave CLI (same shell)
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates git pkg-config libssl-dev build-essential
          # Rust (cargo) so cargo-build-sbf can run cargo metadata
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          # Agave CLI (cargo-build-sbf) v2.3.9
          curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.3.9/agave-install-init-x86_64-unknown-linux-gnu -o agave-install-init
          chmod +x agave-install-init
          ./agave-install-init v2.3.9
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$HOME/.local/share/agave/install/active_release/bin:$PATH"
          # Sanity
          rustc --version
          cargo --version
          which cargo-build-sbf
          cargo-build-sbf --version
          # Build with tag lockfiles to avoid edition-2024 pulls
          cargo-build-sbf --manifest-path programs/stake/Cargo.toml -- --locked
          cargo-build-sbf --manifest-path programs/vote/Cargo.toml -- --locked
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbf-artifacts
          path: target/deploy/*.so
