name: build-sbf
  on:
  workflow_dispatch:
  inputs:
  ref:
  description: 'Git ref (tag/branch/commit)'
  default: 'v2.3.9'
  required: true
  jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout ref
  uses: actions/checkout@v4
  with:
  ref: ${{ github.event.inputs.ref }}
  fetch-depth: 0

        - name: Install Agave CLI v2.3.9
          run: |
            curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.3.9/agave-install-init-x86_64-unknown-linux-gnu -o agave-install-init
            chmod +x agave-install-init
            ./agave-install-init v2.3.9
            echo "$HOME/.local/share/agave/install/active_release/bin" >> $GITHUB_PATH

        - name: Build stake (SBF)
          run: cargo-build-sbf --manifest-path programs/stake/Cargo.toml

        - name: Build vote (SBF)
          run: cargo-build-sbf --manifest-path programs/vote/Cargo.toml

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: sbf-artifacts
            path: target/deploy/*.so
