name: build-sbf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream Agave v2.3.9
        uses: actions/checkout@v4
        with:
          repository: anza-xyz/agave
          ref: v2.3.9
          fetch-depth: 0
      
      - name: Install Agave CLI v2.3.9
        run: |
          set -eux
          curl -sSfL https://github.com/anza-xyz/agave/releases/download/v2.3.9/agave-install-init-x86_64-unknown-linux-gnu -o agave-install-init
          chmod +x agave-install-init
          ./agave-install-init v2.3.9
          echo "$HOME/.local/share/agave/install/active_release/bin" >> "$GITHUB_PATH"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      
      - name: Show tools
        run: |
          set -eux
          which cargo-build-sbf
          cargo-build-sbf --version
      
      - name: Build stake (locked)
        run: |
          set -eux
          cargo-build-sbf --manifest-path programs/stake/Cargo.toml -- --locked
      
      - name: Build vote (locked)
        run: |
          set -eux
          cargo-build-sbf --manifest-path programs/vote/Cargo.toml -- --locked
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbf-artifacts
          path: target/deploy/*.so
